# Generated by Django 3.1.4 on 2021-04-26 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_bank_app', '0002_loan_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loan_data',
        ),
    ]
