# Generated by Django 3.1.4 on 2021-04-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_bank_app', '0003_delete_loan_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types_of_loan', models.CharField(max_length=40)),
                ('bank_name', models.CharField(max_length=70)),
                ('interest_rate', models.CharField(max_length=30)),
                ('processing_fee_range', models.CharField(max_length=40)),
                ('loan_amount', models.CharField(max_length=50)),
                ('tenure_range', models.CharField(max_length=70)),
            ],
        ),
    ]
