# Generated by Django 3.1.4 on 2021-04-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_bank_app', '0004_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('card_type', models.CharField(max_length=50)),
                ('first_year_fee', models.CharField(max_length=50)),
                ('rewards', models.CharField(max_length=50)),
                ('joining_perks', models.CharField(max_length=50)),
            ],
        ),
    ]
