# Generated by Django 3.2.2 on 2021-06-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_bank_app', '0008_alter_contact_us_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpInsert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=500)),
                ('phone', models.IntegerField(max_length=11)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
