# Generated by Django 3.2.2 on 2021-06-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_bank_app', '0009_empinsert'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmpInsert',
            new_name='Contactus',
        ),
        migrations.DeleteModel(
            name='Contact_us',
        ),
    ]
