# Generated by Django 3.2.2 on 2021-08-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_bank_app', '0012_carloaneligibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracbankloan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicants_name', models.CharField(max_length=250)),
                ('applicants_full_name', models.CharField(max_length=200)),
                ('applicants_father_name', models.CharField(max_length=200)),
                ('applicants_mother_name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('contatct_no', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('nid', models.CharField(max_length=100)),
                ('loan_type', models.CharField(max_length=200)),
                ('full_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('p_address', models.CharField(max_length=200)),
                ('second_contact_no', models.CharField(max_length=100)),
                ('organisation_name', models.CharField(max_length=100)),
                ('designation_department', models.CharField(max_length=100)),
                ('office_address', models.CharField(max_length=200)),
                ('allowness', models.CharField(max_length=100)),
                ('additional_income', models.CharField(max_length=100)),
                ('salary_total', models.CharField(max_length=100)),
                ('office_no', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('loan_requested', models.CharField(max_length=100)),
                ('balance_amount', models.CharField(max_length=100)),
                ('payment_source', models.CharField(max_length=100)),
                ('tin_no', models.CharField(max_length=100)),
            ],
        ),
    ]
