# Generated by Django 3.2.2 on 2021-08-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_bank_app', '0014_remove_bracbankloan_loan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
