# Generated by Django 3.2.2 on 2021-08-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_bank_app', '0019_hloanform2_hloanform3_hloanform4_hloanform5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hloanform3',
            name='date_expected',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hloanform3',
            name='expected_possesion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hloanform3',
            name='flat_no',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hloanform3',
            name='floor_size',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hloanform3',
            name='nationality_2',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hloanform3',
            name='property_type',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hloanform3',
            name='utility',
            field=models.CharField(max_length=1000),
        ),
    ]
