# Generated by Django 3.2.2 on 2021-08-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_bank_app', '0020_auto_20210828_0205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='homeloanappform',
        ),
    ]
