# Generated by Django 3.2.2 on 2021-08-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_bank_app', '0022_auto_20210828_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hloanform3',
            new_name='hlform3',
        ),
        migrations.RenameField(
            model_name='hlform3',
            old_name='date_expected',
            new_name='de',
        ),
        migrations.RenameField(
            model_name='hlform3',
            old_name='expected_possesion',
            new_name='ep',
        ),
        migrations.RenameField(
            model_name='hlform3',
            old_name='flat_no',
            new_name='f',
        ),
        migrations.RenameField(
            model_name='hlform3',
            old_name='floor_size',
            new_name='fs',
        ),
        migrations.RenameField(
            model_name='hlform3',
            old_name='nationality_2',
            new_name='n',
        ),
        migrations.RenameField(
            model_name='hlform3',
            old_name='property_type',
            new_name='pt',
        ),
        migrations.RenameField(
            model_name='hlform3',
            old_name='utility',
            new_name='u',
        ),
    ]
