# Generated by Django 3.2.2 on 2021-08-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_bank_app', '0023_auto_20210828_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hlform3',
            old_name='de',
            new_name='date_expected',
        ),
        migrations.RenameField(
            model_name='hlform3',
            old_name='ep',
            new_name='expected_possesion',
        ),
        migrations.RenameField(
            model_name='hlform3',
            old_name='f',
            new_name='flat_no',
        ),
        migrations.RenameField(
            model_name='hlform3',
            old_name='fs',
            new_name='floor_size',
        ),
        migrations.RenameField(
            model_name='hlform3',
            old_name='n',
            new_name='nationality_2',
        ),
        migrations.RenameField(
            model_name='hlform3',
            old_name='pt',
            new_name='property_type',
        ),
        migrations.RenameField(
            model_name='hlform3',
            old_name='u',
            new_name='utility',
        ),
    ]
