# Generated by Django 3.2.2 on 2021-08-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_bank_app', '0025_hloanform3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hlform3',
        ),
    ]
