# Generated by Django 3.2.2 on 2021-08-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_bank_app', '0028_brac_home_loan_form1_brac_home_loan_form2_brac_home_loan_form3_brac_home_loan_form4_brac_home_loan_f'),
        ('Easy_bank_app', '0028_city_credit_card_form1'),
    ]

    operations = [
    ]
