# Generated by Django 3.2.2 on 2021-09-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_bank_app', '0036_city_car_loan_form1_city_car_loan_form2_city_car_loan_form3_city_car_loan_form4_city_car_loan_form5_'),
    ]

    operations = [
        migrations.CreateModel(
            name='city_personal_loan_form1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicants_name', models.CharField(max_length=250)),
                ('applicants_full_name', models.CharField(max_length=200)),
                ('applicants_father_name', models.CharField(max_length=200)),
                ('applicants_mother_name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('contatct_no', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('nid', models.CharField(max_length=100)),
                ('loan_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='city_personal_loan_form2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('p_address', models.CharField(max_length=200)),
                ('second_contact_no', models.CharField(max_length=100)),
                ('second_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='city_personal_loan_form3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=100)),
                ('floor_size', models.CharField(max_length=100)),
                ('flat_no', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('utility', models.CharField(max_length=100)),
                ('expected_possesion', models.CharField(max_length=100)),
                ('date_expected', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='city_personal_loan_form4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_loan', models.CharField(max_length=100)),
                ('loan_in_word', models.CharField(max_length=100)),
                ('balance_amount', models.CharField(max_length=100)),
                ('due_time', models.CharField(max_length=100)),
                ('property_selected', models.CharField(max_length=100)),
                ('contact_2', models.CharField(max_length=100)),
                ('email_3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='city_personal_loan_form5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=100)),
                ('designation_department', models.CharField(max_length=100)),
                ('office_address', models.CharField(max_length=200)),
                ('allowness', models.CharField(max_length=100, null=True)),
                ('additional_income', models.CharField(max_length=100, null=True)),
                ('salary_total', models.CharField(max_length=100, null=True)),
                ('office_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='brac_credit_card_form',
        ),
        migrations.DeleteModel(
            name='city_credit_card_form1',
        ),
        migrations.RenameField(
            model_name='brac_car_loan_form2',
            old_name='city',
            new_name='permanent_address',
        ),
        migrations.RenameField(
            model_name='brac_car_loan_form2',
            old_name='full_address',
            new_name='present_address',
        ),
        migrations.RenameField(
            model_name='brac_car_loan_form3',
            old_name='flat_no',
            new_name='cc_type',
        ),
        migrations.RenameField(
            model_name='brac_car_loan_form3',
            old_name='floor_size',
            new_name='manufacturing_year',
        ),
        migrations.RenameField(
            model_name='brac_car_loan_form3',
            old_name='nationality_2',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='brac_car_loan_form3',
            old_name='property_type',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='brac_car_loan_form4',
            old_name='home_area',
            new_name='reffered_amount',
        ),
        migrations.RenameField(
            model_name='brac_car_loan_form4',
            old_name='loan_requested',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='brac_car_loan_form5',
            old_name='office_address',
            new_name='home_address',
        ),
        migrations.RenameField(
            model_name='brac_car_loan_form5',
            old_name='designation_department',
            new_name='own_house',
        ),
        migrations.RenameField(
            model_name='brac_car_loan_form5',
            old_name='organisation_name',
            new_name='total_monthly_expenses',
        ),
        migrations.RenameField(
            model_name='brac_education_loan_form3',
            old_name='date_expected',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='brac_education_loan_form3',
            old_name='expected_possesion',
            new_name='date_of_complete',
        ),
        migrations.RenameField(
            model_name='brac_education_loan_form3',
            old_name='flat_no',
            new_name='total_duration',
        ),
        migrations.RenameField(
            model_name='brac_education_loan_form3',
            old_name='floor_size',
            new_name='yearly_expenses',
        ),
        migrations.RenameField(
            model_name='brac_education_loan_form4',
            old_name='balance_amount',
            new_name='book_expense',
        ),
        migrations.RenameField(
            model_name='brac_education_loan_form4',
            old_name='home_area',
            new_name='exam_fees',
        ),
        migrations.RenameField(
            model_name='brac_education_loan_form4',
            old_name='loan_requested',
            new_name='scholarship',
        ),
        migrations.RenameField(
            model_name='brac_education_loan_form4',
            old_name='payment_source',
            new_name='tution_fees',
        ),
        migrations.RenameField(
            model_name='brac_education_loan_form5',
            old_name='additional_income',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='brac_education_loan_form5',
            old_name='office_address',
            new_name='hsc_gpa',
        ),
        migrations.RenameField(
            model_name='brac_education_loan_form5',
            old_name='allowness',
            new_name='other_qualification',
        ),
        migrations.RenameField(
            model_name='brac_education_loan_form5',
            old_name='designation_department',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='brac_education_loan_form5',
            old_name='office_no',
            new_name='ssc_gpa',
        ),
        migrations.RenameField(
            model_name='brac_loan_against_property_form4',
            old_name='balance_amount',
            new_name='dues',
        ),
        migrations.RenameField(
            model_name='brac_loan_against_property_form4',
            old_name='loan_requested',
            new_name='other_expenses',
        ),
        migrations.RenameField(
            model_name='brac_personal_loan_form3',
            old_name='flat_no',
            new_name='no_of_property',
        ),
        migrations.RenameField(
            model_name='brac_personal_loan_form3',
            old_name='floor_size',
            new_name='others',
        ),
        migrations.RenameField(
            model_name='brac_personal_loan_form3',
            old_name='nationality_2',
            new_name='property_details',
        ),
        migrations.RenameField(
            model_name='brac_startup_loan_form3',
            old_name='date_expected',
            new_name='idea_type',
        ),
        migrations.RenameField(
            model_name='brac_startup_loan_form3',
            old_name='flat_no',
            new_name='loan_tenure_time',
        ),
        migrations.RenameField(
            model_name='brac_startup_loan_form3',
            old_name='floor_size',
            new_name='startup_type',
        ),
        migrations.RenameField(
            model_name='brac_startup_loan_form4',
            old_name='home_area',
            new_name='loan_amount',
        ),
        migrations.RenameField(
            model_name='brac_startup_loan_form4',
            old_name='loan_requested',
            new_name='loan_in_word',
        ),
        migrations.RenameField(
            model_name='city_car_loan_form3',
            old_name='expected_possesion',
            new_name='amount_of_loan',
        ),
        migrations.RenameField(
            model_name='city_car_loan_form3',
            old_name='flat_no',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='city_car_loan_form3',
            old_name='floor_size',
            new_name='loan_in_word',
        ),
        migrations.RenameField(
            model_name='city_car_loan_form3',
            old_name='property_type',
            new_name='no_of_month_to_close',
        ),
        migrations.RenameField(
            model_name='city_car_loan_form4',
            old_name='balance_amount',
            new_name='car_model',
        ),
        migrations.RenameField(
            model_name='city_car_loan_form4',
            old_name='home_area',
            new_name='loan_percentage',
        ),
        migrations.RenameField(
            model_name='city_car_loan_form4',
            old_name='loan_requested',
            new_name='manufacturing_year',
        ),
        migrations.RenameField(
            model_name='city_education_loan_form3',
            old_name='date_expected',
            new_name='extracuricular_activity',
        ),
        migrations.RenameField(
            model_name='city_education_loan_form3',
            old_name='expected_possesion',
            new_name='hsc_result',
        ),
        migrations.RenameField(
            model_name='city_education_loan_form3',
            old_name='flat_no',
            new_name='ielts_result',
        ),
        migrations.RenameField(
            model_name='city_education_loan_form3',
            old_name='floor_size',
            new_name='ssc_result',
        ),
        migrations.RenameField(
            model_name='city_education_loan_form4',
            old_name='home_area',
            new_name='amount_of_loan',
        ),
        migrations.RenameField(
            model_name='city_education_loan_form4',
            old_name='loan_requested',
            new_name='amount_of_loan_in_word',
        ),
        migrations.RenameField(
            model_name='city_education_loan_form5',
            old_name='designation_department',
            new_name='institute_name',
        ),
        migrations.RenameField(
            model_name='city_education_loan_form5',
            old_name='office_address',
            new_name='institution_address',
        ),
        migrations.RenameField(
            model_name='city_education_loan_form5',
            old_name='organisation_name',
            new_name='loan_duration',
        ),
        migrations.RenameField(
            model_name='city_education_loan_form5',
            old_name='additional_income',
            new_name='scholarship',
        ),
        migrations.RenameField(
            model_name='city_education_loan_form5',
            old_name='salary_total',
            new_name='scholarship_in_words',
        ),
        migrations.RenameField(
            model_name='city_home_loan_form4',
            old_name='balance_amount',
            new_name='area_code',
        ),
        migrations.RenameField(
            model_name='city_home_loan_form4',
            old_name='home_area',
            new_name='city_code',
        ),
        migrations.RenameField(
            model_name='city_home_loan_form4',
            old_name='loan_requested',
            new_name='neutral_landmark',
        ),
        migrations.RenameField(
            model_name='city_home_loan_form4',
            old_name='payment_source',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='brac_car_loan_form2',
            name='p_address',
        ),
        migrations.RemoveField(
            model_name='brac_car_loan_form2',
            name='second_contact_no',
        ),
        migrations.RemoveField(
            model_name='brac_car_loan_form3',
            name='utility',
        ),
        migrations.RemoveField(
            model_name='brac_education_loan_form3',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='brac_education_loan_form3',
            name='utility',
        ),
        migrations.RemoveField(
            model_name='brac_education_loan_form4',
            name='property_selected',
        ),
        migrations.RemoveField(
            model_name='brac_education_loan_form5',
            name='organisation_name',
        ),
        migrations.RemoveField(
            model_name='brac_education_loan_form5',
            name='salary_total',
        ),
        migrations.RemoveField(
            model_name='brac_loan_against_property_form4',
            name='payment_source',
        ),
        migrations.RemoveField(
            model_name='brac_loan_against_property_form4',
            name='property_selected',
        ),
        migrations.RemoveField(
            model_name='brac_personal_loan_form3',
            name='utility',
        ),
        migrations.RemoveField(
            model_name='brac_personal_loan_form4',
            name='home_area',
        ),
        migrations.RemoveField(
            model_name='brac_startup_loan_form3',
            name='nationality_2',
        ),
        migrations.RemoveField(
            model_name='brac_startup_loan_form3',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='city_car_loan_form3',
            name='utility',
        ),
        migrations.RemoveField(
            model_name='city_education_loan_form3',
            name='nationality_2',
        ),
        migrations.RemoveField(
            model_name='city_education_loan_form3',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='city_home_loan_form4',
            name='property_selected',
        ),
        migrations.AddField(
            model_name='brac_car_loan_form2',
            name='mobile',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
