# Generated by Django 3.2.2 on 2021-09-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_bank_app', '0037_auto_20210904_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='brac_credit_card_form1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicants_name', models.CharField(max_length=250)),
                ('applicants_full_name', models.CharField(max_length=200)),
                ('applicants_father_name', models.CharField(max_length=200)),
                ('applicants_mother_name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('contatct_no', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('nid', models.CharField(max_length=100)),
                ('credit_card_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='brac_credit_card_form2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('p_address', models.CharField(max_length=200)),
                ('second_contact_no', models.CharField(max_length=100)),
                ('second_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='brac_credit_card_form3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=100)),
                ('designation_department', models.CharField(max_length=100)),
                ('office_address', models.CharField(max_length=200)),
                ('allowness', models.CharField(max_length=100, null=True)),
                ('additional_income', models.CharField(max_length=100, null=True)),
                ('salary_total', models.CharField(max_length=100, null=True)),
                ('office_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='brac_credit_card_form4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicants_name', models.CharField(max_length=250)),
                ('applicants_full_name', models.CharField(max_length=200)),
                ('applicants_father_name', models.CharField(max_length=200)),
                ('applicants_mother_name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('contatct_no', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('nid', models.CharField(max_length=100)),
                ('credit_card_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='brac_credit_card_form5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=100)),
                ('balance_amount', models.CharField(max_length=200)),
                ('contact_no_2', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='city_credit_card_form1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicants_name', models.CharField(max_length=250)),
                ('applicants_full_name', models.CharField(max_length=200)),
                ('applicants_father_name', models.CharField(max_length=200)),
                ('applicants_mother_name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('contatct_no', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('nid', models.CharField(max_length=100)),
                ('credit_card_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='city_credit_card_form2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('p_address', models.CharField(max_length=200)),
                ('second_contact_no', models.CharField(max_length=100)),
                ('second_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='city_credit_card_form3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=100)),
                ('designation_department', models.CharField(max_length=100)),
                ('office_address', models.CharField(max_length=200)),
                ('allowness', models.CharField(max_length=100, null=True)),
                ('additional_income', models.CharField(max_length=100, null=True)),
                ('salary_total', models.CharField(max_length=100, null=True)),
                ('office_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='city_credit_card_form4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicants_name', models.CharField(max_length=250)),
                ('applicants_full_name', models.CharField(max_length=200)),
                ('applicants_father_name', models.CharField(max_length=200)),
                ('applicants_mother_name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('contatct_no', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('nid', models.CharField(max_length=100)),
                ('credit_card_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='city_credit_card_form5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=100)),
                ('balance_amount', models.CharField(max_length=200)),
                ('contact_no_2', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
