# Generated by Django 3.2.2 on 2021-09-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_bank_app', '0038_brac_credit_card_form1_brac_credit_card_form2_brac_credit_card_form3_brac_credit_card_form4_brac_cre'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
